### ISSUE TITLE
[STF]: Integer Overflow in dim4 Class Causing Runtime Exception

### ISSUE THREAD

**Issue by 19970126ljl** [NVIDIA/cccl#5891]
### Is this a duplicate?

- [x] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Runtime Error

### Component

CUDA Experimental (cudax)

### Describe the bug

CUDA STF applications crash with "Floating point exception (core dumped)" when processing data arrays larger than `INT_MAX` elements due to integer overflow in the `dim4` class.
When creating logical data with more than `INT_MAX` (2,147,483,647) elements, the STF framework fails during data allocation because the `dim4` class uses `int` type for dimension storage, causing overflow and subsequent division by zero errors.

### How to Reproduce

1. Create a test program with array size exceeding `INT_MAX`:

```cpp
#include <cuda/experimental/stf.cuh>
#include <cuda/experimental/__stf/places/blocked_partition.cuh>

using namespace cuda::experimental::stf;

int main() {
    constexpr size_t N = 1ULL << 32;  // 4,294,967,296 elements
    std::vector<double> X(N);
    double* data_X = X.data();
    exec_place_grid where;
    where = exec_place::repeat(exec_place::current_device(), 2);
    auto cdp = data_place::composite(blocked_partition(), where);
    context ctx;
    auto lX = ctx.logical_data(data_X, {N});
    ctx.launch(where, lX.rw(cdp))->*[] __device__(auto t, auto dX) {};
    ctx.finalize();
    return 0;
}
```

2. Compile and run the program 
```bash
nvcc -std=c++17 -expt-relaxed-constexpr --extended-lambda -arch=native -lcuda -lineinfo -O0   -I/path/to/cccl/libcudacxx/include -I/path/to/cccl/cudax/include -I/path/to/cccl/cub -I/path/to/cccl/thrust dim4_int_overflow.cu -o dim4_int_overflow -G -g
```
4. Observe runtime crash: `Floating point exception (core dumped)`
```bash
gdb dim4_int_overflow
# or
./dim4_int_overflow
```

## Expected Behavior

The program should either:
- Successfully handle large arrays (preferred), OR
- Provide a clear error message about size limitations

## Actual Behavior

Runtime crash with "Floating point exception (core dumped)" due to division by zero.

## Root Cause Analysis

The root cause of the integer overflow is a data type mismatch within the CUDA STF framework. The `dim4` class, used for representing data dimensions, stores its `x`, `y`, `z`, and `t` members as `int` types. However, the logical data's shape is represented using `size_t`. When an application processes an array with more than `INT_MAX` elements, the `size_t` value from the data shape is truncated when converted to the `int` members of the `dim4` object.

This overflow occurs specifically in the data allocation path:

**File**: `cccl/cudax/include/cuda/experimental/__stf/stream/interfaces/slice.cuh`
**Function**: `data_allocate`
**Code**: `const dim4 data_dims = this->shape.get_data_dims();`

### Technical Details

1.  **Type Mismatch**: The core issue is the conversion from a `size_t` (which can be 64-bit) to an `int` (32-bit).
2.  **Class Hierarchy**: The `dim4` class inherits from `pos4`, which defines the dimensions `x`, `y`, `z`, and `t` as `int`.
3.  **Overflow and Division by Zero**: When a `size_t` value larger than `INT_MAX` is cast to an `int`, it results in an overflow (often wrapping around to a small or zero value). This incorrect dimension value then leads to a division-by-zero error in subsequent calculations within the `get_executor` function.

### Operating System

Ubuntu 22.04.5 LTS

### nvidia-smi output

+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.01             Driver Version: 535.183.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A800 80GB PCIe          Off | 00000000:9C:00.0 Off |                    0 |
| N/A   37C    P0              67W / 300W |    474MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA A800 80GB PCIe          Off | 00000000:9D:00.0 Off |                    0 |
| N/A   34C    P0              45W / 300W |     58MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+

### NVCC version

nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2025 NVIDIA Corporation
Built on Wed_Apr__9_19:24:57_PDT_2025
Cuda compilation tools, release 12.9, V12.9.41
Build cuda_12.9.r12.9/compiler.35813241_0

**Comment by miscco** [comment]
@19970126ljl Thanks a lot for submitting the bug report, I am not sure whether this is actually a bug or a missing feature of large array support.

**Comment by caugonnet** [comment]
@19970126ljl thanks for catching this ! Indeed the dim4 and pos4 classes used here should probably store size_t instead of int...

If you are trying to dispatch a large array (more than 4G elements) over your machine (or on a single device) that would indeed be problematic.

**Comment by caugonnet** [comment]
@19970126ljl Can you please confirm the issue is fixed on your side ? Thanks again for reporting the issue !

**Comment by 19970126ljl** [comment]
@caugonnet Thanks for the update! I tested the fix, but the issue still exists in [slice.cuh#L564-L586](https://github.com/NVIDIA/cccl/blob/86d5d5b4d61f4b28238bf282040358d4266c9766/cudax/include/cuda/experimental/__stf/internal/slice.cuh#L564-L586).
In get_data_dims(), the size_t values from extents.extent(i) are cast to int. This may lead to overflow when the extent is larger than INT_MAX. Could you please take another look?

**Comment by caugonnet** [comment]
https://github.com/NVIDIA/cccl/pull/6015 should fix the remaining issues, i've now tested locally (reducing the type to 2 chars to limit the memory required to test on my local system). Thanks again @19970126ljl this is much appreciated !

**Comment by caugonnet** [comment]
@19970126ljl Hopefully i merged the fix for the remaining issues you had ...

**Comment by 19970126ljl** [comment]
@caugonnet Thank you for the fix! I noticed a small typo in thread configuration conversion that needs correction — please see [PR #6089 ](https://github.com/NVIDIA/cccl/pull/6089)for the update.
